version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    depends_on:
      - php

  php:
    build: php
    volumes:
    - public-php:/var/www/public

  mysql:
    build: docker/mysql
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
  public-php:
