version: "3.8"

services:
  nginx:
    build: nginx
    volumes:
    - public-php:/var/www/public
    ports:
      - 80:80
    depends_on:
      - php

  php:
    build: php
    volumes:
    - public-php:/var/www/public

  mysql:
    build: mysql
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
  public-php:
