version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    depends_on:
      - php

  php:
    build: docker/php
    volumes:
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - ./public/src:/var/www/public/src
    - ./public/index.php:/var/www/public/index.php
    - ./public/config:/var/www/public/config
    environment:
      PROJECT_DIR: /var/www/public

  mysql:
    build: docker/mysql
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
