version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    depends_on:
      - php

  php:
    build: docker/php
    volumes:
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - ./public/src:/var/www/public/src
    - ./public/index.php:/var/www/public/index.php
    - ./public/config:/var/www/public/config

  mysql:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test

volumes:
  db-volume:
