generate_products:
  path: /product/create-products
  defaults: {_controller: 'App\Controller\ProductController::createProducts'}
  methods:  [POST]

create_order:
  path: /order/create
  defaults: {_controller: 'App\Controller\OrderController::createOrder'}
  methods:  [POST]

pay_order:
  path: /order/pay
  defaults: {_controller: 'App\Controller\OrderController::payOrder'}
  methods:  [PUT]
